name: Deploy

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: 'ubuntu-latest'
    outputs:
      cache: ${{ steps.yarn.outputs.dir }}
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get yarn cache directory path
        id: yarn
        run: echo "::set-output name=dir::$(yarn cache dir)"

  lint:
    runs-on: 'ubuntu-latest'
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ needs.setup.outputs.cache }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-next-js-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-next-js-${{ hashFiles('**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - name: lint
        run: yarn lint

  preview:
    environment: preview
    needs: setup
    runs-on: 'ubuntu-latest'
    outputs:
      url: ${{ steps.deploy.outputs.preview-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ needs.setup.outputs.cache }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-next-js-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-next-js-${{ hashFiles('**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - name: Pull configuration
        run: yarn vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Set env
        run: |
          echo true                             | yarn vercel env add MOCK preview --token=${VERCEL_TOKEN} -y
          echo ${{ secrets.JWT_SECRET }}        | yarn vercel env add JWT_SECRET preview --token=${VERCEL_TOKEN} -y
          echo foobar                           | yarn vercel env add GITHUB_CLIENT_SECRET preview --token=${VERCEL_TOKEN} -y
          echo ${{ secrets.CDN_URL }}           | yarn vercel env add CDN_URL preview --token=${VERCEL_TOKEN} -y
          echo ${{ secrets.AUTHORIZED_USERS }}  | yarn vercel env add AUTHORIZED_USERS preview --token=${VERCEL_TOKEN} -y
          echo ${{ secrets.S3_BUCKET }}         | yarn vercel env add S3_BUCKET preview --token=${VERCEL_TOKEN} -y
          echo ${{ secrets.S3_KEY }}            | yarn vercel env add S3_KEY preview --token=${VERCEL_TOKEN} -y
          echo ${{ secrets.S3_KEY_SECRET }}     | yarn vercel env add S3_KEY_SECRET preview --token=${VERCEL_TOKEN} -y
          echo ${{ secrets.S3_URL }}            | yarn vercel env add S3_URL preview --token=${VERCEL_TOKEN} -y
      - name: Build
        run: yarn vercel build
        env:
          NEXT_PUBLIC_GITHUB_CLIENT_ID: foobar
          NEXT_PUBLIC_GITHUB_USERNAME: ${{ secrets.NEXT_PUBLIC_GITHUB_USERNAME }}
          NEXT_PUBLIC_INSTAGRAM_USERNAME: ${{ secrets.NEXT_PUBLIC_INSTAGRAM_USERNAME }}
          NEXT_PUBLIC_LINKEDIN_USERNAME: ${{ secrets.NEXT_PUBLIC_LINKEDIN_USERNAME }}
          NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}
          NEXT_PUBLIC_NAME: ${{ secrets.NEXT_PUBLIC_NAME }}
      - name: Deploy
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          github-comment: false
          vercel-args: --prebuilt
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}

  test:
    needs: [setup, lint, preview]
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ needs.setup.outputs.cache }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-next-js-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-next-js-${{ hashFiles('**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          browser: chrome
          config: baseUrl=${{ needs.preview.outputs.url }}
          install: false
          record: true

  cleanup:
    needs: [setup, preview, test]
    runs-on: 'ubuntu-latest'
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ needs.setup.outputs.cache }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-next-js-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-next-js-${{ hashFiles('**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile
      - name: Delete deployment
        run: yarn vercel rm ${{ needs.preview.outputs.url }} -y --token=${VERCEL_TOKEN}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
