name: Production

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy:
    needs: test
    environment:
      name: production
      url: https://tregan.me
    runs-on: 'ubuntu-latest'
    steps:
      - name: Get yarn cache directory path
        id: cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache resources
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.cache.outputs.dir }}
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.json', '**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile && yarn add vercel --prefer-offline
      - name: Pull configuration
        run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      - name: Deploy
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          github-comment: false
          vercel-args: --prod
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
