name: Test

on: [push]

jobs:
  test:
    environment: test
    runs-on: 'ubuntu-latest'
    env:
      AUTHORIZED_USERS: ${{ secrets.AUTHORIZED_USERS }}
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_CLIENT_SECRET: foobar
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MOCK: true
      NEXT_PUBLIC_GITHUB_CLIENT_ID: foobar
      NEXT_PUBLIC_GITHUB_USERNAME: ${{ secrets.NEXT_PUBLIC_GITHUB_USERNAME }}
      NEXT_PUBLIC_INSTAGRAM_USERNAME: ${{ secrets.NEXT_PUBLIC_INSTAGRAM_USERNAME }}
      NEXT_PUBLIC_LINKEDIN_USERNAME: ${{ secrets.NEXT_PUBLIC_LINKEDIN_USERNAME }}
      NEXT_PUBLIC_NAME: ${{ secrets.NEXT_PUBLIC_NAME }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_KEY_SECRET: ${{ secrets.S3_KEY_SECRET }}
      S3_URL: ${{ secrets.S3_URL }}
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - name: Build
        run: yarn build
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          install: false
          record: true
          start: yarn start
          wait-on: 'http://localhost:3000'
